name: 'Ellx sync'
description: 'Sync Github repo with Ellx cloud'
inputs:
  key:
    description: 'Secret key for the project'
    required: true
  ellxUrl:
    description: 'Ellx API URL'
    required: false
    default: 'https://api.ellx.io'
outputs:
  status:
    description: 'Job status'
  files:
    description: 'List of synced files'
runs:
  using: 'node13'
  main: 'dist/index.js'
